#Requires AutoHotkey v2.0

global PowerScribe := "PowerScribe"
global Epic := "Hyperspace"
;global RadCalc := "RadCalc"
global RadCalcAAo := "RadCalc-AAo"
global RadCalcDEXA := "RadCalc-DEXA"
global Intellispace := "Philips IntelliSpace Portal"
global MSEdge := "Edge"
global radcalc_ingest_button := "543 128"
global max_button := "46 1064"
global ChangePACS := "Change Healthcare"
; global Capture2Text := "..\Applications\Capture2Text\Capture2Text_CLI.exe"
global Capture2Text_Directory := "C:\Users\B909907\OneDrive - Kaiser Permanente\@Tyler\Efficiency\Applications\Capture2Text"
global Capture2Text_Executable := "Capture2Text_CLI.exe"